### ISSUE TITLE
Issue in running compute_CVrisk() function in CVrisk package 

### ISSUE THREAD

**Issue by hussaifm** [vcastro/CVrisk#2]
Hi Victor, I am reaching out to you because I'm using your package CVrisk for medical research. I have a dataset n=320 subjects. I wanted to add the risk factor scores for each patient in my data frame. I get error every time I run the compute_CVrisk() function. I debugged as much as I can but nothing works.

I releveled the gender to _male, female_ instead of _female, male_  but didn't work
I made sure of the data types totchol and any other numerical variables are numeric. I tried both ways for gender and race factor and character. I renamed my values to white, aa, other instead of White, African American, Other

This is my code: 
compute_CVrisk(risk_selected1,
               age = "age", race = "race", gender = "gender", bmi = "bmi", sbp = "sbp",
               hdl = "hdl", totchol = "totchol", bp_med = "bp_med", smoker = "smoker",
               diabetes = "diabetes")

and this is the error message:
Error in (function (race = "white", gender = c("male", "female"), age,  : 
  argument "age" is missing, with no default

when I use the example data in the package data(sample_data) the code works perfectly. 

Do you have any reasons in mind? Is there anyway to solve this?

Thank you for your time I appreciate your help

**Comment by vcastro** [comment]
Hi Fatima,

You may not have the package loaded in your environment yet?

Try calling  `library(CVrisk)` and then running the function above.

or you could try:

```
CVrisk::compute_CVrisk(sample_data,
               age = "age", race = "race", gender = "gender", bmi = "bmi", sbp = "sbp",
               hdl = "hdl", totchol = "totchol", bp_med = "bp_med", smoker = "smoker",
               diabetes = "diabetes")
```

**Comment by hussaifm** [comment]
> Hi Fatima,
> 
> You may not have the package loaded in your environment yet?
> 
> Try calling `library(CVrisk)` and then running the function above.
> 
> or you could try:
> 
> ```
> CVrisk::compute_CVrisk(sample_data,
>                age = "age", race = "race", gender = "gender", bmi = "bmi", sbp = "sbp",
>                hdl = "hdl", totchol = "totchol", bp_med = "bp_med", smoker = "smoker",
>                diabetes = "diabetes")
> ```

**Comment by vcastro** [comment]
Ah, you edited the original post with a new error message after I had responded.

Based on updated error, my guess is that your input dataset does not have an age column.  Can you post the results of `names(risk_selected1)`?

**Comment by hussaifm** [comment]
Ok you're right I had a typo in age i wrote age instead of Age. But still that is not the problem  

names(risk_selected1)
 [1] "Age"      "race"     "gender"   "bmi"      "sbp"      "hdl"      "totchol"  "bp_med"   "smoker"   "diabetes"

 sapply(risk_selected1, class)
        Age        race      gender         bmi         sbp         hdl     totchol      bp_med      smoker    diabetes 
  "numeric" "character" "character"   "numeric"   "numeric"   "numeric"   "numeric"   "numeric"   "numeric"   "numeric" 


> risk_selected1%>%
+     compute_CVrisk(age = "Age", race = "race", gender = "gender", bmi = "bmi", sbp = "sbp",
+                hdl = "hdl", totchol = "totchol", bp_med = "bp_med", smoker = "smoker",
+                diabetes = "diabetes")

Error in (function (race = "white", gender = c("male", "female"), age,  : 
  race must be either 'aa' or 'white'

table(risk_selected1$race)
$race

   aa other white 
   86    42   192 

table(risk_selected1$gender)

female   male 
   173    147

**Comment by vcastro** [comment]
The issues seems to be the 'other' race category. 

The FRS simple risk score only has different formulas for white and aa.  Online calculators do have an 'other' category but these use the same risk coefficients as the 'white' category.

There is an error in the documentation for the function that indicates that 'other' is allowed that I need to fix (or convert set other to white in the function).  In the meantime, you can update the other category to white in your dataset which should allow the function to work.

**Comment by hussaifm** [comment]
Ok that makes sense, I updated the other group to white. but another error came up:

> risk_selected1%>%
     compute_CVrisk(age = "Age", race = "race", gender = "gender", bmi = "bmi", sbp = "sbp",
                hdl = "hdl", totchol = "totchol", bp_med = "bp_med", smoker = "smoker",
                diabetes = "diabetes")
Error in if (!is.numeric(totchol) | totchol < 1 | totchol > 999 | missing(totchol)) { : 
  missing value where TRUE/FALSE needed

totchol is numeric 

$totchol

 80  92  95 101 107 108 109 110 111 116 120 121 125 126 127 128 131 132 133 134 135 138 139 142 144 145 146 149 150 151 152 157 159 161 162 164 166 167 168 170 
  1   1   1   1   1   1   2   1   1   1   1   1   1   1   1   1   1   1   1   2   1   1   1   2   1   1   1   2   2   3   1   1   1   1   1   1   1   1   2   1 
171 176 178 183 192 193 194 197 198 202 203 209 211 224 237 239 260 265 271 304 
  1   1   1   1   1   1   2   1   1   1   3   1   1   1   1   1   1   1   1   1

**Comment by vcastro** [comment]
What class is your totchol column?

Run: `class(risk_selected1$totchol)`

**Comment by hussaifm** [comment]
> class(risk_selected1$totchol)
[1] "numeric"

**Comment by vcastro** [comment]
Hmm, puzzling.  Are you using the version from CRAN (1.0) or from Github (1.1)?

**Comment by hussaifm** [comment]
No I didn't use it from Github I'm bit unfamiliar with it. I installed it from CRAN yes, I don't know what you mean by (1.0)
This message appears when I load the package:

> library(CVrisk)
Warning message:
package ‘CVrisk’ was built under R version 4.1.1

**Comment by hussaifm** [comment]
My R version is here:

R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by vcastro** [comment]
I'm not really sure why you are getting this error.  It might help to install the more recent version from Github:

```
install.packages("devtools")
devtools::install_github("vcastro/CVRisk")`
```
The Github version has some updates in parameter checking.

**Comment by hussaifm** [comment]
I think the problem the problem is the install.packages("devtools") doesn't work on my computer. I'll try to solve this and see.

Thanks 👍

**Comment by hussaifm** [comment]
Actually, I knew what's the problem. 

My dataset has many NA's in most of the variables except age and race. When I deleted those rows entirely they worked. I should have thought about this before because the actual website https://tools.acc.org/ascvd-risk-estimator-plus/#!/calculate/estimate/ won't give any results if we had NA for any variable. If showed you a simulated data we could figure this out faster, but glad I could get the results finally.

Thanks anyway for your help.

**Comment by vcastro** [comment]
Hi Fatima, glad you were able to figure it out.  Thanks for the feedback.  I've worked a bit on the package to more gracefully handle missing values.  The newest version on github incorporates these changes and hope to submit to CRAN soon.
