### ISSUE TITLE
gender must be either 'male' or 'female' error message

### ISSUE THREAD

**Issue by laouvi** [vcastro/CVrisk#3]
Hello, 
using CVrisk functions ascvd_10y_frs and ascvd_10y_frs_simple I am getting the error message "gender must be either 'male' or 'female'" even though the gender is coded as male and female. This is also the case with the sample_data provided in the package. What am I doing wrong?
Best,
laouvi

**Comment by vcastro** [comment]
Hi Iaouvi,

Can you include the line of code you are trying to run?

Also, did you try the example provided in the help page:

``` r
library(CVrisk)

ascvd_10y_frs(
  gender = "male", age = 55,
  hdl = 50, totchol = 213, sbp = 140,
  bp_med = 0, smoker = 0, diabetes = 0
)
```
Victor

**Comment by laouvi** [comment]
Hello Victor, 
your sample with one individual is working. I would like to calculate the scores for several individuals in a data frame. I have tried this:

> ascvd_10y_frs(sample_data)

Fehler in ascvd_10y_frs(sample_data) : 
  gender must be either 'male' or 'female'

**Comment by vcastro** [comment]
Try using the `r compute_CVrisk` function which accepts a dataframe:

```r
compute_CVrisk(sample_data,
               scores = c("ascvd_10y_frs", "ascvd_10y_frs_simple"),
               age = "age", race = "race", gender = "gender", bmi = "BMI", sbp = "sbp",
               hdl = "hdl", totchol = "totchol", bp_med = "bp_med", smoker = "smoker",
               diabetes = "diabetes", lipid_med = "lipid_med",
               fh_heartattack = "fh_heartattack", cac = "cac"
)
```

The inputs are the column names of your dataframe.
