### ISSUE TITLE
Scores not returning for 2013 ACC/AHA score - unsure why not?

### ISSUE THREAD

**Issue by emilie-theberge** [vcastro/CVrisk#5]
Hello!

I have a dataframe where I've made sure all NA rows are removed, variables are appropriately labeled per your units and labels indicated, but I don't know why the 2013 ACC/AHA score isn't being returned. 

My input looks like this: (my dataframe is called ascvd_2017, want the scores to be printed as new variables in ascvd_2017_scores).

`ascvd_2017_scores <- compute_CVrisk(ascvd_2017, scores = c("ascvd_10y_accaha"), race = "race", gender = "gender", age = "age", totchol = "totchol", hdl = "hdl", sbp = "sbp", bp_med = "bp_med", smoker = "smoker", diabetes = "diabetes")`

Output is my dataframe with a new variable column 'ascvd_10y_accaha' but every value is NA.

Interestingly, when I removed the c("ascvd_10y_accaha"), the ascvd_10y_frs scores were returned but not any of the other scores.
`ascvd_2017_scores <- compute_CVrisk(ascvd_2017, race = "race", gender = "gender", age = "age", totchol = "totchol", hdl = "hdl", sbp = "sbp", bp_med = "bp_med", smoker = "smoker", diabetes = "diabetes")`

I tried recoding people with "other" races as "white" and that didn't change anything. I don't have any aa in my dataset.

str() shows:
 $ race    : chr  "white" "white" "white" "white" ...
 $ gender  : chr  "male" "female" "female" "male" ...
 $ age     : num  49 78 57 63 52 50 55 73 57 28 ...
 $ totchol : num  70.1 71.7 105.4 49.7 67.4 ...
 $ hdl     : num  35.3 33.9 25.2 20.2 25.4 ...
 $ sbp     : num  122 145 132 92 127 119 128 120 117 106 ...
 $ bp_med  : num  1 1 0 1 1 1 1 1 1 0 ...
 $ smoker  : num  0 0 0 0 0 0 0 0 0 1 ...
 $ diabetes: num  0 0 0 0 0 0 0 0 0 0 ...

etc. 

What do you think I need to change to return an accaha score?
Thanks in advance for your help!

**Comment by vcastro** [comment]
Not sure what the issue is here.  The fact that FRS scores are returned but not the ACCAHA scores would point to an issue with race in your dataset.   But it does appear correct in your str() output.

ACCAHA score defaults to white race when it is not provided so you might want to try removing the race parameter in the compute_CVrisk call to see if it will return a score.  

Using the sample data example, this call will return an ACCAHA score:

```r
compute_CVrisk(
  sample_data,
  scores = c("ascvd_10y_accaha"),
  age = "age",
  gender = "gender",
  bmi = "BMI",
  sbp = "sbp",
  hdl = "hdl",
  totchol = "totchol",
  bp_med = "bp_med",
  smoker = "smoker",
  diabetes = "diabetes",
  lipid_med = "lipid_med",
  fh_heartattack = "fh_heartattack",
  cac = "cac"
)
```

**Comment by emilie-theberge** [comment]
I took out the race parameter and still no ACCAHA scores returned :(.
I tried the function using the sample data and can indeed see the scores returned for the sample data set, so the function is working in my environment.

Per page 2 of [your manual](https://cran.rstudio.com/web/packages/CVrisk/CVrisk.pdf), I assumed the other variables listed (bmi, lipid med, fh_heartattack, cac) aren't needed for calculating the ACCAHA score. Still, I tried re-running it including all these variables in the function anyways (even though I don't have columns for them) and no ACCAHA scores returned:

`ascvd_2017_scores_2 <- compute_CVrisk(
  ascvd_2017, 
  scores = c("ascvd_10y_accaha"), 
  age = "age", 
  gender = "gender",
  bmi = "BMI",
  sbp = "sbp",
  hdl = "hdl", 
  totchol = "totchol", 
  bp_med = "bp_med", 
  smoker = "smoker", 
  diabetes = "diabetes",  
  lipid_med = "lipid_med", 
  fh_heartattack = "fh_heartattack", 
  cac = "cac")`

Are there any other suggestions you have or information I can share that would be helpful in troubleshooting this? 

Also, weirdly, there are a bunch of FRS NAs returned for people who I would expect would have a score. Attached a screenshot...

![ascvd_scores_screenshot](https://user-images.githubusercontent.com/128954883/227837054-e253dfc6-5896-4512-9e27-071c4412b0aa.png)

**Comment by vcastro** [comment]
I think I see the problem.  It looks like your totchol values may be in a different unit?  The valid values to be used in the calculation are 130-320 mg/dL.  

We probably need some better documentation on the limits.  The function replaces invalid values with NA to silently fail the calculation which is confusing (but allows large scale calculations when only some values are invalid).  You can see the valid values for the ACCAHA formula in the code here: https://github.com/vcastro/CVrisk/blob/master/R/ascvd_10y_accaha.R

**Comment by emilie-theberge** [comment]
That was indeed the issue!! I had miscoded the conversion calculation (my measurements were initially entered as mmol/L and I had to convert). Helpful to see the raw code, thanks for redirecting there too, so I may see the upper and lower limits to explain why some people have NAs returned for their scores. Many thanks Victor!
